apiVersion: v1
kind: ServiceAccount
metadata:
  name: flux-notifications-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flux-notifications-role
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - triggers
  - clusterinterceptors
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - clusterinterceptors
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  - taskruns
  - clusterinterceptors
  - pods
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - impersonate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-notifications-clusterrole
rules:
- apiGroups:
  - triggers.tekton.dev
  resources:
  - clustertriggerbindings
  - eventlisteners
  - triggerbindings
  - triggertemplates
  - triggers
  - clusterinterceptors
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - pipelineresources
  - taskruns
  - clusterinterceptors
  - pods
  verbs:
  - create
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-notifications-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flux-notifications-role
subjects:
- kind: ServiceAccount
  name: flux-notifications-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: flux-notifications-clusterrole-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flux-notifications-clusterrole
subjects:
- kind: ServiceAccount
  name: flux-notifications-sa
  namespace: default